version: '3.8'

services:
  app:
    build: .
    image: chaima59/firstjob-app:latest  # Ajoutez cette ligne
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=your_root_password
      - DATABASE_NAME=your_database_name

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
    ports:
      - "3306:3306"
